#####################################################
#
#   WEBGUY PORTAL FRAMEWORK CI/CD PIPELINE
#
#

stages:
    - development   #Pushes the Portal Framework code to dev.webguyinternet.com server.
    - staging       #Pushes Portal Framework code to non-production sites using the Portal Framework on the Dev server.
    - production    #Pushes Portal Framework code to production server(s).

#### PORTAL-FRAMEWORK DEVELOPMENT ####
deploy-to-development-server:
        stage: development
        tags:
            - webguy-development-server #Only runner with this tag will run this pipeline
        only: 
            refs:
                - branches #Changes to branches trigger pipeline
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
                - "*.md" #Ignore .md files
        script:
            - if [ -z "$portal_development_root" ]; then echo "Need to set webroot as GitLab CI/CD variable" && exit 1; fi
            - sudo rsync -rv ./ $portal_development_root/ --exclude-from=./_exclusions.txt --delete
            - sudo chown admin:admin $portal_development_root -R

#### FAIRYLAND DEVELOPMENT ####
update-fairyland-dev-portal-framework:
        stage: staging
        tags:
            - webguy-development-server #Only runner with this tag will run this pipeline
        only: 
            refs:
                - branches #Changes to branches trigger pipeline
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
                - "*.md" #Ignore .md files
        when: manual #Runner will only run with manual intervention
        image: node:latest
        script:
            - sudo npm install uglifyjs-folder -g #Install uglifyjs-folder if not already installed
            - uglifyjs-folder ./framework/js -o ./framework/js/all.min.js -p "**/*.js" --comments #Minify all JS in the folder
            - uglifyjs-folder ./framework/vendor/datepicker-lightpick/js -o ./framework/vendor/datepicker-lightpick/js/lightpick.min.js -p "**/*.js" #Minify custom lightpick JS
            - find ./framework/js -type f -name "*.js" -not -name "all.min.js" -delete #Remove the unminified JS
            - if [ -z "$fairyland_admin_dev_webroot" ]; then echo "Need to set webroot as GitLab CI/CD variable" && exit 1; fi #Verify env var is set
            - sudo rsync -rv ./framework/ $fairyland_admin_dev_webroot/framework --delete --exclude-from=./_exclusions.txt #Sync and overwrite framework directory
            - sudo rsync -rv ./ $fairyland_admin_dev_webroot --exclude 'framework' --exclude-from=./_exclusions.txt #Sync root directory without overwrite
            - sudo chown fairyland:fairyland $fairyland_admin_dev_webroot -R

#### FAIRYLAND PRODUCTION ####
update-fairyland-production-portal-framework:
  environment:
      name: production
  stage: production
  tags:
      - penny-webserver #Only runner with this tag will run this pipeline
  except:
      changes: #Ignore changes to the following files
        - _exclusings.txt
        - .* #Ignore dot files
        - "*.md" #Ignore .md files
  only:
      refs:
        - branches #Changes to branches trigger pipeline
  when: manual #Runner will only run with manual intervention
  image: node:latest
  script:
    - sudo npm install uglifyjs-folder -g #Install uglifyjs-folder if not already installed
    - uglifyjs-folder ./framework/js -o ./framework/js/all.min.js -p "**/*.js" --comments #Minify all JS in the folder
    - uglifyjs-folder ./framework/vendor/datepicker-lightpick/js -o ./framework/vendor/datepicker-lightpick/js/lightpick.min.js -p "**/*.js" #Minify custom lightpick JS
    - find ./framework/js -type f -name "*.js" -not -name "all.min.js" -delete #Remove the unminified JS
    - if [ -z "$fairyland_admin_production_webroot" ]; then echo "Need to set webroot" && exit 1; fi #Verify webroot env var is set
    - sudo rsync -rv ./framework/ $fairyland_admin_dev_webroot/framework --delete --exclude-from=./_exclusions.txt #Sync and overwrite framework directory
    - sudo rsync -rv ./ $fairyland_admin_dev_webroot --exclude 'framework' --exclude-from=./_exclusions.txt #Sync root directory without overwrite
    - sudo chown 1004:users $fairyland_admin_production_webroot -R #Change ownerships