#####################################################
#
#   WEBGUY PORTAL FRAMEWORK CI/CD PIPELINE
#
#

stages:
    - development   #Pushes the Portal Framework code to dev.webguyinternet.com server.
    - staging       #Pushes Portal Framework code to non-production sites using the Portal Framework on the Dev server.
    - production    #Pushes Portal Framework code to production server(s).

#### PORTAL-FRAMEWORK DEVELOPMENT ####
deploy-to-development-server:
        stage: development
        tags:
            - webguy-development-server #Only runner with this tag will run this pipeline
        only: 
            refs:
                - branches #Changes to branches trigger pipeline
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
        script:
            - if [ -z "$portal_development_root" ]; then echo "Need to set webroot as GitLab CI/CD variable" && exit 1; fi
            - sudo rsync -rv ./ $portal_development_root/ --exclude-from=./_exclusions.txt --delete
            - sudo chown admin:admin $portal_development_root -R

#### FAIRYLAND DEVELOPMENT ####
update-fairyland-dev-portal-framework:
        stage: staging
        tags:
            - webguy-development-server #Only runner with this tag will run this pipeline
        only: 
            refs:
                - branches #Changes to branches trigger pipeline
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
        when: manual #Runner will only run with manual intervention
        script:
            - if [ -z "$fairyland_portal_root" ]; then echo "Need to set webroot as GitLab CI/CD variable" && exit 1; fi
            - sudo rsync -rv ./framework/ $fairyland_portal_root/framework --delete --exclude-from=./_exclusions.txt #Sync and overwrite framework directory
            - sudo rsync -rv ./ $fairyland_portal_root --exclude 'framework' --exclude-from=./_exclusions.txt #Sync root directory without overwrite
            - sudo chown fairyland:fairyland $fairyland_portal_root -R

#### FAIRYLAND PRODUCTION ####
update-fairyland-production-portal-framework:
        environment:
            name: fairyland-production
        stage: production
        tags:
            - fairyland-production #Only runner with this tag will run this pipeline
        only: 
            refs:
                - branches #Changes to branches trigger pipeline
        variables:
            GIT_STRATEGY: clone #Fixes bug specific to CentOS7
        when: manual #Runner will only run with manual intervention
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
        script:
            - if [ -z "$fairyland_prod_portal_root" ]; then echo "Need to set webroot as GitLab CI/CD variable" && exit 1; fi
            - sudo rsync -rv ./framework/ $fairyland_prod_portal_root/framework --delete --exclude-from=./_exclusions.txt #Sync and overwrite framework directory
            - sudo rsync -rv ./ $fairyland_prod_portal_root --exclude 'framework' --exclude-from=./_exclusions.txt #Sync root directory without overwrite
            - sudo chown fairyland:fairyland $fairyland_prod_portal_root -R